### ISSUE TITLE
Mobile UI for 2.8.0

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#1088]
```[tasklist]
### Tasks
- [x] Create Project Window
- [x] Compiler Window
- [ ] Social Window
- [ ] Extension Library
- [ ] Extension Install Location
- [ ] Prompt Window
- [ ] Alert Window
- [ ] Confirm Window
- [ ] Swapping between sidebar and tabs
- [ ] Dropdown Window
```
