### ISSUE TITLE
Rewrite Text Editor

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#1091]
```[tasklist]
### Tasks
- [x] View Documentation
- [x] Got to Definition
- [x] Go to Symbol
- [x] Change all Occurrences
- [x] Format Document
- [x] Copy / Cut / Paste
- [x] Syntax Highlighting
- [x] JSON Auto Completions
- [ ] https://github.com/bridge-core/editor/issues/1116
- [x] Molang Auto Completions
- [x] Snippets
- [x] JS Types
- [x] Lang Auto Completions
```

**Comment by outercloudstudio** [comment]
I need to actually test the theory but I believe there will be issues once we try to implement two windows side by side because when we apply schemas for a file it clears all the other schemas. We'll need to track which schemas go to which file. We also need to track which schemas are in use so we can update those if something like the index updates while using that schema.

**Comment by outercloudstudio** [comment]
> I need to actually test the theory but I believe there will be issues once we try to implement two windows side by side because when we apply schemas for a file it clears all the other schemas. We'll need to track which schemas go to which file. We also need to track which schemas are in use so we can update those if something like the index updates while using that schema.

Turns out I already accounted for this so no need to worry about this.

**Comment by outercloudstudio** [comment]
I also discovered that a lightning cache script and schema script can write to the same file. I'll have to discuss this with @ExDrill to see if we should support this or if this should be not intended.

**Comment by outercloudstudio** [comment]
> I also discovered that a lightning cache script and schema script can write to the same file. I'll have to discuss this with [@ExDrill](https://github.com/ExDrill) to see if we should support this or if this should be not intended.

After discussion we decided that this is intended.

**Comment by outercloudstudio** [comment]
Something that remains to do is have the schema scripts that reference file content react to the file changing. I think that this will just be done with a file system events instead of rerunning the schema scripts for model changes.

**Comment by outercloudstudio** [comment]
> I also discovered that a lightning cache script and schema script can write to the same file. I'll have to discuss this with [@ExDrill](https://github.com/ExDrill) to see if we should support this or if this should be not intended.

After further investigation I've discovered that schema scripts overwrite the schemas generated from lightning cache.

**Comment by outercloudstudio** [comment]
> Something that remains to do is have the schema scripts that reference file content react to the file changing. I think that this will just be done with a file system events instead of rerunning the schema scripts for model changes.

This now works.

**Comment by outercloudstudio** [comment]
Remember this for the command language:
https://github.com/bridge-core/editor-packages/issues/51

**Comment by outercloudstudio** [comment]
https://github.com/Microsoft/monaco-editor/issues/918#issuecomment-398343425
