### ISSUE TITLE
Reimplement dragging files and folder

### ISSUE THREAD

**Issue by outercloudstudio** [bridge-core/editor#1238]
```[tasklist]
### Tasks
- [x] Dragging files
- [x] Dropping files next to files
- [x] Dragging folders
- [x] Dropping files into root
- [x] Holding over folder to open
- [x] Investigate where drop file preview should show
```
